const bearer = "Bearer";

const getTime = () => {
  let today = new Date();
  let date =
    today.getDate() + "-" + (today.getMonth() + 1) + "-" + today.getFullYear();
  let time =
    today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
  return (dateTime = date + " " + time);
};

const extractToken = (req) => {
  if (
    req.headers.authorization &&
    req.headers.authorization.split(" ")[0] === bearer
  ) {
    return req.headers.authorization.split(" ")[1];
  } else if (req.query && req.query.token) {
    return req.query.token;
  }
  return null;
};

let locationMaintenance = {
  data: [
    {
      akeyId: 0,
      ascId: "VN007629-2-S",
      countryCode: "VN",
      ascName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI THÁI HÀ",
      ascPhoneNo: "18001503",
      ascFaxNo: null,
      ascPostalCode: "100000",
      emailAddr: "ctthaiha.hanoi@gmail.com",
      repairableProductCode:
        "CRA,DBM,DEH,GHP,PAC,PAH,PAT,SRA,SRH,WRA,ARC,CAS,ELC,ERN,GOR,MWO,OTR,OTH,FRD,KRE,REF,SBS,STL,CLN,CVC,HST,STC,DRR,DRW,W/M,WPF,DSM,DST,HTV",
      evaluationPointNo: 0,
      ascLatitudeValue: "21.0297982",
      ascLongitudeValue: "105.8410819",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HA NOI",
      pScDiv: "ASC",
      stateName: "VIET NAM",
      address1:
        "SỐ 3, CAO BÁ QUÁT, PHƯỜNG ĐIỆN BIÊN, QUẬN BA ĐÌNH, THÀNH PHỐ HÀ NỘI, VIỆT NAM",
      address3: "ASC_Common",
      address:
        "SỐ 3, CAO BÁ QUÁT, PHƯỜNG ĐIỆN BIÊN, QUẬN BA ĐÌNH, THÀNH PHỐ HÀ NỘI, VIỆT NAM, HA NOI, VIET NAM, 100000",
      eliteName: "",
      productCodes:
        "CRA,DBM,DEH,GHP,PAC,PAH,PAT,SRA,SRH,WRA,ARC,CAS,ELC,ERN,GOR,MWO,OTR,OTH,FRD,KRE,REF,SBS,STL,CLN,CVC,HST,STC,DRR,DRW,W/M,WPF,DSM,DST,HTV",
      localeCode: "VN",
      categoryId: "",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/VN007629-2-S",
      ascLgSvcFlag: null,
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 0.9,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "AQI_INTERNAL",
      countryCode: "VN",
      ascName: "LGC Dam Quang Trung",
      ascPhoneNo: "18001503",
      ascFaxNo: ".",
      ascPostalCode: "100000",
      repairableProductCode:
        "OTR,MWO,DST,HTV,MEP,CMN,MNT,NNT,CDM,GSM,HSD,WCD,WLL,OFA,OTH,NTB,KRE,REF,SBS,CTV,DSN,LCD,LCL,PDP,PRJ,TLV,CLN,CVC,STC,DVD,VPJ,DRR,DRW,W/M,WPF,CRA,DBM,DEH,GHP,PAC,PAH,PAT,SRA,SRH,WRA,AUD,HTH,CDR,CAS,ELC,ERN,GOR,DSM,FRD",
      evaluationPointNo: 0,
      ascLatitudeValue: "21.0085757",
      ascLongitudeValue: "105.8363722",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HÀ NỘI",
      pScDiv: "ASC",
      stateName: "Đồng Bằng Sông Hồng",
      distance: ".",
      address1:
        "Tầng 1 ,Tòa nhà Phúc Đồng, Đường Đàm Quang Trung, Phường Phúc Đồng, Quận Long Biên, Hà Nội",
      address:
        "Tầng 1 ,Tòa nhà Phúc Đồng, Đường Đàm Quang Trung, Phường Phúc Đồng, Quận Long Biên, Hà Nội, HÀ NỘI, Đồng Bằng Sông Hồng, 100000",
      eliteName: "",
      productCodes:
        "OTR,MWO,DST,HTV,MEP,CMN,MNT,NNT,CDM,GSM,HSD,WCD,WLL,OFA,OTH,NTB,KRE,REF,SBS,CTV,DSN,LCD,LCL,PDP,PRJ,TLV,CLN,CVC,STC,DVD,VPJ,DRR,DRW,W/M,WPF,CRA,DBM,DEH,GHP,PAC,PAH,PAT,SRA,SRH,WRA,AUD,HTH,CDR,CAS,ELC,ERN,GOR,DSM,FRD",
      localeCode: "VN",
      categoryId: "",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/AQI_INTERNAL",
      ascLgSvcFlag: null,
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 1.6,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "AQE_INTERNAL",
      countryCode: "VN",
      ascName: "LGC Le Van Luong",
      ascPhoneNo: "18001503",
      ascFaxNo: ".",
      ascPostalCode: "100000",
      repairableProductCode:
        "W/M,DRW,CRA,DBM,DEH,GHP,PAC,PAH,PAT,SRA,SRH,WRA,AUD,HTH,CDR,CAS,ELC,ERN,GOR,MWO,OTR,DSM,DST,HTV,MEP,CMN,MNT,NNT,CDM,GSM,HSD,WCD,WLL,OFA,OTH,NTB,KRE,REF,SBS,CTV,DSN,LCD,LCL,PDP,PRJ,TLV,CLN,CVC,STC,DVD,VPJ,DRR,WPF,FRD",
      evaluationPointNo: 0,
      ascLatitudeValue: "21.0123984",
      ascLongitudeValue: "105.8122717",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HÀ NỘI",
      pScDiv: "ASC",
      stateName: "Đồng Bằng Sông Hồng",
      distance: ".",
      address1: "SỐ 27 LÊ VĂN LƯƠNG, PHƯỜNG NHÂN CHÍNH, QUẬN THANH XUÂN, HN",
      address:
        "SỐ 27 LÊ VĂN LƯƠNG, PHƯỜNG NHÂN CHÍNH, QUẬN THANH XUÂN, HN, HÀ NỘI, Đồng Bằng Sông Hồng, 100000",
      siteAddr: null,
      eliteName: "",
      longitude: null,
      ascRouteMap: null,
      productCodes:
        "W/M,DRW,CRA,DBM,DEH,GHP,PAC,PAH,PAT,SRA,SRH,WRA,AUD,HTH,CDR,CAS,ELC,ERN,GOR,MWO,OTR,DSM,DST,HTV,MEP,CMN,MNT,NNT,CDM,GSM,HSD,WCD,WLL,OFA,OTH,NTB,KRE,REF,SBS,CTV,DSN,LCD,LCL,PDP,PRJ,TLV,CLN,CVC,STC,DVD,VPJ,DRR,WPF,FRD",
      localeCode: "VN",
      categoryId: "",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/AQE_INTERNAL",
      ascLgSvcFlag: null,
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 2.8,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "307767",
      countryCode: "VN",
      ascName: "LGSAV EHP Service",
      repairableProductCode: "PAT,SRA,SRH,WRA,ARC,CRA,DBM,DEH,GHP,PAC,PAH",
      evaluationPointNo: 0,
      ascLatitudeValue: "21.032723",
      ascLongitudeValue: "105.7984797",
      corporationCode: "LGSAV",
      displayOrderNo: 0,
      cityName: "HN",
      pScDiv: "DSC",
      address1:
        " Unit O3517, 35th Floor, Keangnam Honoi Landmark Tower, Plot E6, Cau Giay new urban area, Me Tri ward Nam tu Liem",
      address:
        "Unit O3517, 35th Floor, Keangnam Honoi Landmark Tower, Plot E6, Cau Giay new urban area, Me Tri ward Nam tu Liem, HN",
      localeCode: "VN",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/307767",
      ascLgSvcFlag: null,
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 4.1,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "267395",
      countryCode: "VN",
      ascName: "LGEVH HN SVC SUPPORTING (WH)",
      repairableProductCode:
        "LCD,LCL,DST,HTV,MEP,CMN,MNT,NNT,NTB,CTV,DSN,PDP,PRJ,TLV,DVD,VPJ",
      evaluationPointNo: 0,
      ascLatitudeValue: "21.0173263",
      ascLongitudeValue: "105.7840071",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HN",
      pScDiv: "DSC",
      address1:
        "35th Flr., Keangnam Landmark 72, Plot E6, Pham Hung Str., Cau Giay Dist., Ha Noi, Viet Nam  ",
      address:
        "35th Flr., Keangnam Landmark 72, Plot E6, Pham Hung Str., Cau Giay Dist., Ha Noi, Viet Nam, HN",
      productCodes:
        "LCD,LCL,DST,HTV,MEP,CMN,MNT,NNT,NTB,CTV,DSN,PDP,PRJ,TLV,DVD,VPJ",
      localeCode: "VN",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/267395",
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 5.5,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "267399",
      countryCode: "VN",
      ascName: "LGEVH HN SVC NORTH NETWORK",
      repairableProductCode:
        "DSM,DST,HTV,MEP,DVD,VPJ,CTV,DSN,LCD,LCL,PDP,PRJ,TLV",
      evaluationPointNo: 0,
      ascLatitudeValue: "21.0173263",
      ascLongitudeValue: "105.7840071",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HN",
      pScDiv: "DSC",
      address1:
        "35th Flr., Keangnam Landmark 72, Plot E6, Pham Hung Str., Cau Giay Dist., Ha Noi, Viet Nam  ",
      address:
        "35th Flr., Keangnam Landmark 72, Plot E6, Pham Hung Str., Cau Giay Dist., Ha Noi, Viet Nam, HN",
      eliteName: "",
      productCodes: "DSM,DST,HTV,MEP,DVD,VPJ,CTV,DSN,LCD,LCL,PDP,PRJ,TLV",
      localeCode: "VN",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/267399",
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 5.5,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "VN008171-S",
      countryCode: "VN",
      ascName: "CÔNG TY TNHH HI-M SOLUTEK VIỆT NAM",
      ascPhoneNo: "18001503",
      ascPostalCode: "100004",
      emailAddr: "thuhuong.vu@lge.com;baochau.phan@lge.com",
      repairableProductCode: "PAC,PAH,DBM,CRA,PAT,SRA,SRH,DEH,GHP,WRA",
      evaluationPointNo: 0,
      ascLatitudeValue: "21.0163377",
      ascLongitudeValue: "105.7840463",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HA NOI",
      pScDiv: "ASC",
      stateName: "VIET NAM",
      address1:
        "Tầng 35, Tòa nhà Keangnam Landmark 72, Đường Phạm Hùng, Phường Mễ Trì, Quận Nam Từ Liêm, Thành phố Hà Nội, Việt Nam",
      address3: "ASC_CAC",
      address:
        "Tầng 35, Tòa nhà Keangnam Landmark 72, Đường Phạm Hùng, Phường Mễ Trì, Quận Nam Từ Liêm, Thành phố Hà Nội, Việt Nam, HA NOI, VIET NAM, 100004",
      eliteName: "",
      productCodes: "PAC,PAH,DBM,CRA,PAT,SRA,SRH,DEH,GHP,WRA",
      localeCode: "VN",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/VN008171-S",
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 5.5,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "VN008194-2-S",
      countryCode: "VN",
      ascName: "CÔNG TY CỔ PHẦN CLEANPRO VIỆT NAM",
      ascPhoneNo: "18001503",
      ascPostalCode: "100000",
      emailAddr: "thuydt.cleanpro@gmail.com",
      repairableProductCode: "W/M,DRW,DRR",
      evaluationPointNo: 0,
      ascLatitudeValue: "20.9880561",
      ascLongitudeValue: "105.8888435",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HA NOI",
      pScDiv: "ASC",
      stateName: "VIET NAM",
      address1:
        "Số 16, Ngõ 169 Phố Ngũ Nhạc, Phường Lĩnh Nam, Quận Hoàng Mai, Thành Phố Hà Nội, Việt Nam",
      address:
        "Số 16, Ngõ 169 Phố Ngũ Nhạc, Phường Lĩnh Nam, Quận Hoàng Mai, Thành Phố Hà Nội, Việt Nam, HA NOI, VIET NAM, 100000",
      siteAddr: null,
      productCodes: "W/M,DRW,DRR",
      localeCode: "VN",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/VN008194-2-S",
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 6.6,
      ascPhoneTxt: "Điện thoại",
    },
    {
      akeyId: 0,
      ascId: "VN008590-1-S",
      countryCode: "VN",
      ascName: "CONG TY TNHH DAU TU VA XUAT NHAP KHAU TAN THINH PHAT",
      ascPhoneNo: "0977377510",
      ascFaxNo: null,
      ascPostalCode: "100000",
      emailAddr: "ttbhttp.hanoi1@gmail.com",
      repairableProductCode:
        "CVC,CLN,DVD,VPJ,DRR,DRW,W/M,WPF,GHP,PAC,PAH,PAT,SRA,SRH,WRA,AUD,HTH,CAS,ELC,ERN,GOR,MWO,OTR,DSM,DST,HTV,MEP,MNT,OFA,OTH,NTB,FRD,KRE,REF,SBS,CTV,DSN,LCD,LCL,PDP,PRJ,TLV,STC,STL,SRM",
      evaluationPointNo: 0,
      ascLatitudeValue: "20.9787466",
      ascLongitudeValue: "105.7619209",
      corporationCode: "LGEVH",
      displayOrderNo: 0,
      cityName: "HA NOI",
      pScDiv: "ASC",
      stateName: "VIET NAM",
      distance: null,
      address1:
        "C49 Ô 16, LK12, KHU ĐÔ THỊ GELEXIMCO, ĐƯỜNG LÊ TRỌNG TẤN, PHƯỜNG DƯƠNG NỘI, QUẬN HÀ ĐÔNG, TP HÀ NỘI",
      address3: "ASC_Common",
      address:
        "C49 Ô 16, LK12, KHU ĐÔ THỊ GELEXIMCO, ĐƯỜNG LÊ TRỌNG TẤN, PHƯỜNG DƯƠNG NỘI, QUẬN HÀ ĐÔNG, TP HÀ NỘI, HA NOI, VIET NAM, 100000",
      productCodes:
        "CVC,CLN,DVD,VPJ,DRR,DRW,W/M,WPF,GHP,PAC,PAH,PAT,SRA,SRH,WRA,AUD,HTH,CAS,ELC,ERN,GOR,MWO,OTR,DSM,DST,HTV,MEP,MNT,OFA,OTH,NTB,FRD,KRE,REF,SBS,CTV,DSN,LCD,LCL,PDP,PRJ,TLV,STC,STL,SRM",
      localeCode: "VN",
      searchLatitudeValue: "21.022742162309548",
      searchLongitudeValue: "105.83696369999998",
      ascUrl: "/vn/tro-giup/theo-doi-sua-chua-trung-tam/VN008590-1-S",
      dmsFlag: "Y",
      directServiceFlag: "N",
      calcDistance: 9.2,
      ascPhoneTxt: "Điện thoại",
    },
  ],
};

module.exports = {
  default_role: 1,
  DEFAULT_ID: 1,
  USER_DEFAULT_ACTIVE: 1,
  USER_DEFAULT_UNACTIVE: 2,
  STATUS_PAYMENTR: 1,
  locationMaintenance,
  getTime,
  extractToken,
};
